### PR TITLE
Updated logging information.

### PR DESCRIPTION
**Pull request by RedInquisitive**
I updated your logging to match my old version.
I also fixed that GFX garbage flash at the beginning (again).
Feel free to review the changes. I tried to make it merge friendly :sunglasses:

### CODE REVIEW

**Comment by ihaveamac** [comment]
`launcher.zip` is supposed to exist in the repository because that's how the updater works at the moment. mashers has a script create the .zip containing the launcher and the updater.

**Comment by ihaveamac** [comment]
it would also make it easier for those who can't or don't want to use the updater to get the latest version, though he hasn't linked to it yet...

**Comment by RedInquisitive** [comment]
@ihaveamac Oh shoot! I thought I restored that before I created the pull request! Doh, I'll put it back!

**Comment by ihaveamac** [comment]
nevermind, 7bded62 does indeed have it.

**Comment by RedInquisitive** [comment]
@ihaveamac Yeah, I cleaned the repository just for me. Before I create a merge request, however, I'll add all of the files back. 
Before I work on anything else I'll have to wait for @mashers to tag issues as help wanted so I don't accidentally work on the same thing as him.

**Comment by ihaveamac** [comment]
I just noticed that launcher.zip in this has the older updater.

@mashers once this is merged, you should use gitpush again so a new .zip is created.

**Comment by mashers** [comment]
I'm a bit confused here ;) Could you summarise what this pull request will do if I merge it?

**Comment by ihaveamac** [comment]
a quick scroll tells me that it's logging more information.

**Comment by RedInquisitive** [comment]
@mashers Sure thing!
- I added some logging information where I felt it was neccisary to help the debug process go a little bit somoother (950d896)
- I refactored logtext.c so the logging file isn't opened and closed a million times whenever something is logged (I kept the old code there as well) (950d896)
- If a single theme is selected, BGM doesn't play twice when the launcher is opened (950d896)
- If a theme is changed and that theme is missing audio files that the previous theme had, they will be unloaded insted of playing random chuncks of memory (c669d8d)
That's about it. Give me a second and I'll go fetch your changes and merge them into the branch again.

**Comment by RedInquisitive** [comment]
both c8c99be and  91f1c10 now cover your changes.

**Comment by RedInquisitive** [comment]
@mashers I merged your changes for you.

**Comment by RedInquisitive** [comment]
@mashers did it work?

**Pull request merged**
