### PR TITLE
updater 2.04

### PR DESCRIPTION
**Pull request by ihaveamac**
#### Version 2.03 available via wireless Internet connection and Releases includes the following improvements:

* Further improvements to overall updater stability and other minor adjustments have been made to enhance the user experience
* More jabs at Nintendo's update changelog
* Adds notice in case the server has disabled the updater

### CODE REVIEW

**Comment by ihaveamac** [comment]
please don't merge this yet. I'm going to make another update soon.

**Comment by ihaveamac** [comment]
2.04 will check for `/gridlauncher/glinfo.txt` and, by default, install to `/boot.3dsx` if it's missing. before, it would just lock up at a black screen.

**Comment by mashers** [comment]
Hi mate, is this ready to merge now?

**Comment by ihaveamac** [comment]
yes it is.

**Comment by mashers** [comment]
Great! I've got some changes to push first (I don't think I can pull before I push) so I'll do it shortly.

**Pull request merged**
